# wrangler.toml

name = "garden"
# 告诉 Cloudflare Pages 构建产物的静态文件在哪里
pages_build_output_dir = ".vercel/output/static"

# 保持这些运行时配置
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]
