export interface Crop {
  id: string
  name: string
  baseValue: number
  categories: string[]
  rarity: "Common" | "Uncommon" | "Rare" | "Legendary" | "Mythical" | "Divine" | "Prismatic" | "Transcendent"
  description: string
  season?: string
  growthTime?: string
}

export interface Mutation {
  id: string
  name: string
  bonus: number // Changed from multiplier to bonus for environmental mutations
  type: "growth" | "environmental" | "temperature" // Updated with temperature type
  categories: string[]
  rarity: "Common" | "Uncommon" | "Rare" | "Legendary" | "Mythical" | "Divine" | "Prismatic" | "Transcendent"
  description: string
  color: string
}

// Real Grow a Garden crop data (same as before)
export const crops: Crop[] = [
  // Common Crops
  {
    id: "carrot",
    name: "Carrot",
    baseValue: 15,
    categories: ["Basic Crops", "Root Vegetables", "Garden Staples"],
    rarity: "Common",
    description: "A classic orange root vegetable, perfect for beginners",
    season: "Spring",
    growthTime: "2 hours",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    baseValue: 14,
    categories: ["Basic Crops", "Berries", "Sweet Fruits"],
    rarity: "Common",
    description: "Sweet red berries with tiny seeds on the surface",
    season: "Spring",
    growthTime: "3 hours",
  },

  // Uncommon Crops
  {
    id: "blueberry",
    name: "Blueberry",
    baseValue: 18,
    categories: ["Berries", "Antioxidant Rich", "Bush Fruits"],
    rarity: "Uncommon",
    description: "Small blue berries packed with nutrients and flavor",
    season: "Summer",
    growthTime: "4 hours",
  },
  {
    id: "rose",
    name: "Rose",
    baseValue: 4513,
    categories: ["Flowers", "Ornamental", "Fragrant"],
    rarity: "Uncommon",
    description: "Classic red rose with thorny stems and sweet fragrance",
    season: "Spring",
    growthTime: "8 hours",
  },
  {
    id: "orange-tulip",
    name: "Orange Tulip",
    baseValue: 767,
    categories: ["Flowers", "Bulb Plants", "Colorful"],
    rarity: "Uncommon",
    description: "Vibrant orange tulip with elegant cup-shaped blooms",
    season: "Spring",
    growthTime: "6 hours",
  },
  {
    id: "stonebite",
    name: "Stonebite",
    baseValue: 31588,
    categories: ["Rare Flowers", "Hardy Plants", "Stone Gardens"],
    rarity: "Uncommon",
    description: "Tough flowering plant that grows in rocky terrain",
    season: "Fall",
    growthTime: "12 hours",
  },

  // Rare Crops
  {
    id: "tomato",
    name: "Tomato",
    baseValue: 27,
    categories: ["Vegetables", "Vine Plants", "Kitchen Garden"],
    rarity: "Rare",
    description: "Juicy red fruit commonly used as a vegetable",
    season: "Summer",
    growthTime: "5 hours",
  },
  {
    id: "daffodil",
    name: "Daffodil",
    baseValue: 903,
    categories: ["Flowers", "Spring Bulbs", "Yellow Blooms"],
    rarity: "Rare",
    description: "Bright yellow spring flower with trumpet-shaped center",
    season: "Spring",
    growthTime: "7 hours",
  },
  {
    id: "cauliflower",
    name: "Cauliflower",
    baseValue: 36,
    categories: ["Vegetables", "Brassicas", "White Vegetables"],
    rarity: "Rare",
    description: "White flowering head vegetable with dense florets",
    season: "Fall",
    growthTime: "8 hours",
  },
  {
    id: "raspberry",
    name: "Raspberry",
    baseValue: 90,
    categories: ["Berries", "Cane Fruits", "Tart Fruits"],
    rarity: "Rare",
    description: "Red aggregate berries with sweet-tart flavor",
    season: "Summer",
    growthTime: "6 hours",
  },
  {
    id: "foxglove",
    name: "Foxglove",
    baseValue: 18050,
    categories: ["Flowers", "Tall Plants", "Medicinal"],
    rarity: "Rare",
    description: "Tall spikes of tubular purple flowers",
    season: "Summer",
    growthTime: "10 hours",
  },
  {
    id: "peace-lily",
    name: "Peace Lily",
    baseValue: 22000,
    categories: ["Flowers", "Indoor Plants", "White Blooms"],
    rarity: "Rare",
    description: "Elegant white spathe flowers with dark green leaves",
    season: "Year-round",
    growthTime: "12 hours",
  },
  {
    id: "corn",
    name: "Corn",
    baseValue: 36,
    categories: ["Grains", "Tall Plants", "Staple Crops"],
    rarity: "Rare",
    description: "Golden kernels on tall stalks with silk tassels",
    season: "Summer",
    growthTime: "9 hours",
  },
  {
    id: "paradise-petal",
    name: "Paradise Petal",
    baseValue: 25000,
    categories: ["Exotic Flowers", "Rare Blooms", "Paradise Plants"],
    rarity: "Rare",
    description: "Mystical flower petals from paradise gardens",
    season: "Eternal",
    growthTime: "15 hours",
  },

  // Legendary Crops
  {
    id: "watermelon",
    name: "Watermelon",
    baseValue: 2708,
    categories: ["Large Fruits", "Melons", "Summer Crops"],
    rarity: "Legendary",
    description: "Large juicy fruit with red flesh and black seeds",
    season: "Summer",
    growthTime: "16 hours",
  },
  {
    id: "pumpkin",
    name: "Pumpkin",
    baseValue: 3069,
    categories: ["Large Fruits", "Gourds", "Halloween"],
    rarity: "Legendary",
    description: "Large orange gourd perfect for carving",
    season: "Fall",
    growthTime: "18 hours",
  },
  {
    id: "avocado",
    name: "Avocado",
    baseValue: 30685,
    categories: ["Tree Fruits", "Healthy Fats", "Tropical"],
    rarity: "Legendary",
    description: "Creamy green fruit rich in healthy oils",
    season: "Tropical",
    growthTime: "24 hours",
  },
  {
    id: "apple",
    name: "Apple",
    baseValue: 248,
    categories: ["Tree Fruits", "Orchard", "Classic Fruits"],
    rarity: "Legendary",
    description: "Crisp red apple from traditional orchards",
    season: "Fall",
    growthTime: "20 hours",
  },
  {
    id: "green-apple",
    name: "Green Apple",
    baseValue: 271,
    categories: ["Tree Fruits", "Orchard", "Tart Fruits"],
    rarity: "Legendary",
    description: "Tart green apple with crisp texture",
    season: "Fall",
    growthTime: "20 hours",
  },
  {
    id: "banana",
    name: "Banana",
    baseValue: 1579,
    categories: ["Tropical Fruits", "Tree Fruits", "Potassium Rich"],
    rarity: "Legendary",
    description: "Yellow curved tropical fruit in bunches",
    season: "Tropical",
    growthTime: "22 hours",
  },
  {
    id: "lilac",
    name: "Lilac",
    baseValue: 31588,
    categories: ["Flowers", "Fragrant", "Purple Blooms"],
    rarity: "Legendary",
    description: "Fragrant purple flower clusters on woody stems",
    season: "Spring",
    growthTime: "25 hours",
  },
  {
    id: "aloe-vera",
    name: "Aloe Vera",
    baseValue: 62272,
    categories: ["Succulents", "Medicinal", "Desert Plants"],
    rarity: "Legendary",
    description: "Healing succulent with thick, gel-filled leaves",
    season: "Desert",
    growthTime: "30 hours",
  },
  {
    id: "bamboo",
    name: "Bamboo",
    baseValue: 3610,
    categories: ["Grasses", "Fast Growing", "Asian Plants"],
    rarity: "Legendary",
    description: "Fast-growing woody grass with hollow stems",
    season: "Tropical",
    growthTime: "28 hours",
  },
  {
    id: "rafflesia",
    name: "Rafflesia",
    baseValue: 3159,
    categories: ["Exotic Flowers", "Parasitic", "Giant Blooms"],
    rarity: "Legendary",
    description: "World's largest flower with distinctive smell",
    season: "Rainforest",
    growthTime: "35 hours",
  },
  {
    id: "horned-dinoshroom",
    name: "Horned Dinoshroom",
    baseValue: 62272,
    categories: ["Mushrooms", "Prehistoric", "Rare Fungi"],
    rarity: "Legendary",
    description: "Ancient mushroom species with horn-like protrusions",
    season: "Prehistoric",
    growthTime: "40 hours",
  },
  {
    id: "boneboo",
    name: "Boneboo",
    baseValue: 127380,
    categories: ["Mystical Plants", "Bone Plants", "Dark Magic"],
    rarity: "Legendary",
    description: "Mysterious plant that grows from ancient bones",
    season: "Underworld",
    growthTime: "48 hours",
  },

  // Mythical Crops
  {
    id: "peach",
    name: "Peach",
    baseValue: 271,
    categories: ["Stone Fruits", "Tree Fruits", "Fuzzy Fruits"],
    rarity: "Mythical",
    description: "Soft, fuzzy fruit with sweet orange flesh",
    season: "Summer",
    growthTime: "26 hours",
  },
  {
    id: "pineapple",
    name: "Pineapple",
    baseValue: 1805,
    categories: ["Tropical Fruits", "Spiky Fruits", "Sweet & Tart"],
    rarity: "Mythical",
    description: "Spiky tropical fruit with sweet yellow flesh",
    season: "Tropical",
    growthTime: "32 hours",
  },
  {
    id: "guanabana",
    name: "Guanabana",
    baseValue: 65431,
    categories: ["Exotic Fruits", "Tropical", "Spiky Fruits"],
    rarity: "Mythical",
    description: "Large spiky fruit with creamy white flesh",
    season: "Tropical",
    growthTime: "45 hours",
  },
  {
    id: "coconut",
    name: "Coconut",
    baseValue: 361,
    categories: ["Tropical Fruits", "Palm Fruits", "Hard Shell"],
    rarity: "Mythical",
    description: "Hard-shelled tropical fruit with coconut water",
    season: "Tropical",
    growthTime: "30 hours",
  },
  {
    id: "cactus",
    name: "Cactus",
    baseValue: 3069,
    categories: ["Succulents", "Desert Plants", "Spiky Plants"],
    rarity: "Mythical",
    description: "Spiky desert plant adapted to arid conditions",
    season: "Desert",
    growthTime: "35 hours",
  },
  {
    id: "dragon-fruit",
    name: "Dragon Fruit",
    baseValue: 4287,
    categories: ["Exotic Fruits", "Cactus Fruits", "Pink Fruits"],
    rarity: "Mythical",
    description: "Exotic pink fruit with white flesh and black seeds",
    season: "Tropical",
    growthTime: "38 hours",
  },
  {
    id: "mango",
    name: "Mango",
    baseValue: 5866,
    categories: ["Tropical Fruits", "Tree Fruits", "Sweet Fruits"],
    rarity: "Mythical",
    description: "Sweet tropical fruit with orange flesh",
    season: "Tropical",
    growthTime: "40 hours",
  },
  {
    id: "kiwi",
    name: "Kiwi",
    baseValue: 2482,
    categories: ["Vine Fruits", "Fuzzy Fruits", "Green Flesh"],
    rarity: "Mythical",
    description: "Small brown fuzzy fruit with green flesh",
    season: "Fall",
    growthTime: "34 hours",
  },
  {
    id: "bell-pepper",
    name: "Bell Pepper",
    baseValue: 4964,
    categories: ["Peppers", "Colorful Vegetables", "Sweet Peppers"],
    rarity: "Mythical",
    description: "Sweet, crunchy peppers in various colors",
    season: "Summer",
    growthTime: "36 hours",
  },
  {
    id: "prickly-pear",
    name: "Prickly Pear",
    baseValue: 6318,
    categories: ["Cactus Fruits", "Desert Plants", "Spiky Fruits"],
    rarity: "Mythical",
    description: "Edible fruit from prickly pear cactus",
    season: "Desert",
    growthTime: "42 hours",
  },
  {
    id: "pink-lily",
    name: "Pink Lily",
    baseValue: 58663,
    categories: ["Flowers", "Lilies", "Pink Blooms"],
    rarity: "Mythical",
    description: "Elegant pink lily with large fragrant blooms",
    season: "Summer",
    growthTime: "50 hours",
  },
  {
    id: "purple-dahlia",
    name: "Purple Dahlia",
    baseValue: 67688,
    categories: ["Flowers", "Purple Blooms", "Complex Flowers"],
    rarity: "Mythical",
    description: "Complex purple flower with layered petals",
    season: "Fall",
    growthTime: "52 hours",
  },
  {
    id: "firefly-fern",
    name: "Firefly Fern",
    baseValue: 64980,
    categories: ["Ferns", "Glowing Plants", "Mystical"],
    rarity: "Mythical",
    description: "Magical fern that glows like fireflies at night",
    season: "Mystical",
    growthTime: "48 hours",
  },

  // Divine Crops
  {
    id: "grape",
    name: "Grape",
    baseValue: 7085,
    categories: ["Vine Fruits", "Wine Grapes", "Cluster Fruits"],
    rarity: "Divine",
    description: "Sweet grapes growing in clusters on vines",
    season: "Fall",
    growthTime: "55 hours",
  },
  {
    id: "loquat",
    name: "Loquat",
    baseValue: 7220,
    categories: ["Tree Fruits", "Asian Fruits", "Orange Fruits"],
    rarity: "Divine",
    description: "Small orange fruit with sweet, tangy flavor",
    season: "Spring",
    growthTime: "58 hours",
  },
  {
    id: "mushroom",
    name: "Mushroom",
    baseValue: 136278,
    categories: ["Fungi", "Forest Plants", "Edible Mushrooms"],
    rarity: "Divine",
    description: "Sacred mushroom with divine properties",
    season: "Forest",
    growthTime: "72 hours",
  },
  {
    id: "pepper",
    name: "Pepper",
    baseValue: 7220,
    categories: ["Spices", "Hot Peppers", "Spicy Plants"],
    rarity: "Divine",
    description: "Fiery pepper with intense heat and flavor",
    season: "Summer",
    growthTime: "60 hours",
  },
  {
    id: "cacao",
    name: "Cacao",
    baseValue: 10830,
    categories: ["Tree Fruits", "Chocolate Source", "Tropical"],
    rarity: "Divine",
    description: "Sacred cacao pods, source of chocolate",
    season: "Tropical",
    growthTime: "65 hours",
  },
  {
    id: "feijoa",
    name: "Feijoa",
    baseValue: 11733,
    categories: ["Exotic Fruits", "Green Fruits", "Aromatic"],
    rarity: "Divine",
    description: "Aromatic green fruit with unique flavor",
    season: "Fall",
    growthTime: "68 hours",
  },
  {
    id: "pitcher-plant",
    name: "Pitcher Plant",
    baseValue: 28880,
    categories: ["Carnivorous Plants", "Exotic", "Insect Eaters"],
    rarity: "Divine",
    description: "Carnivorous plant that traps insects",
    season: "Rainforest",
    growthTime: "75 hours",
  },
  {
    id: "sunflower",
    name: "Sunflower",
    baseValue: 144400,
    categories: ["Flowers", "Giant Flowers", "Oil Seeds"],
    rarity: "Divine",
    description: "Massive flower that follows the sun",
    season: "Summer",
    growthTime: "80 hours",
  },
  {
    id: "fossilight",
    name: "Fossilight",
    baseValue: 79420,
    categories: ["Mystical Plants", "Glowing", "Ancient"],
    rarity: "Divine",
    description: "Ancient plant that glows with fossilized light",
    season: "Ancient",
    growthTime: "85 hours",
  },

  // Prismatic Crops
  {
    id: "beanstalk",
    name: "Beanstalk",
    baseValue: 25270,
    categories: ["Climbing Plants", "Giant Plants", "Magical"],
    rarity: "Prismatic",
    description: "Magical beanstalk that grows to the clouds",
    season: "Magical",
    growthTime: "90 hours",
  },
  {
    id: "ember-lily",
    name: "Ember Lily",
    baseValue: 60166,
    categories: ["Fire Flowers", "Glowing", "Elemental"],
    rarity: "Prismatic",
    description: "Lily that burns with eternal flame",
    season: "Elemental",
    growthTime: "95 hours",
  },
  {
    id: "elephant-ears",
    name: "Elephant Ears",
    baseValue: 69493,
    categories: ["Large Leaves", "Tropical", "Giant Plants"],
    rarity: "Prismatic",
    description: "Massive leaves shaped like elephant ears",
    season: "Tropical",
    growthTime: "100 hours",
  },
  {
    id: "burning-bud",
    name: "Burning Bud",
    baseValue: 63175,
    categories: ["Fire Plants", "Buds", "Elemental"],
    rarity: "Prismatic",
    description: "Flower bud that burns with inner fire",
    season: "Elemental",
    growthTime: "98 hours",
  },

  // Transcendent Crops
  {
    id: "bone-blossom",
    name: "Bone Blossom",
    baseValue: 157938,
    categories: ["Transcendent", "Bone Plants", "Ultimate"],
    rarity: "Transcendent",
    description: "The ultimate flower that blooms from ancient bones",
    season: "Transcendent",
    growthTime: "120 hours",
  },
]

// Updated mutations with proper categorization
export const mutations: Mutation[] = [
  // Growth Mutations (multipliers, only one allowed)
  {
    id: "gold",
    name: "Gold",
    bonus: 20,
    type: "growth",
    categories: ["Precious", "Rare"],
    rarity: "Legendary",
    description: "Random 1% chance golden mutation (×20 multiplier)",
    color: "#FCD34D",
  },
  {
    id: "rainbow",
    name: "Rainbow",
    bonus: 50,
    type: "growth",
    categories: ["Magical", "Rare"],
    rarity: "Legendary",
    description: "Random 0.1% chance rainbow mutation (×50 multiplier)",
    color: "#EC4899",
  },

  // Temperature Mutations (weather-related temperature effects)
  {
    id: "chilled",
    name: "Chilled",
    bonus: 1,
    type: "temperature",
    categories: ["Cold", "Weather"],
    rarity: "Common",
    description: "Affected by frost weather conditions (+1 bonus)",
    color: "#60A5FA",
  },
  {
    id: "frozen",
    name: "Frozen",
    bonus: 9,
    type: "temperature",
    categories: ["Ice", "Cold"],
    rarity: "Rare",
    description: "Wet crops frozen during frost weather (+9 bonus)",
    color: "#3B82F6",
  },
  {
    id: "burnt",
    name: "Burnt",
    bonus: 3,
    type: "temperature",
    categories: ["Fire", "Heat"],
    rarity: "Uncommon",
    description: "Cooked by owl pets with cooking abilities (+3 bonus)",
    color: "#EA580C",
  },
  {
    id: "cooked",
    name: "Cooked",
    bonus: 24,
    type: "temperature",
    categories: ["Food", "Heat"],
    rarity: "Rare",
    description: "Fully cooked by owl pets (+24 bonus)",
    color: "#DC2626",
  },
  {
    id: "molten",
    name: "Molten",
    bonus: 24,
    type: "temperature",
    categories: ["Fire", "Extreme Heat"],
    rarity: "Rare",
    description: "Admin-exclusive volcano event mutation (+24 bonus)",
    color: "#DC2626",
  },
  {
    id: "sundried",
    name: "Sundried",
    bonus: 84,
    type: "temperature",
    categories: ["Sun", "Heat"],
    rarity: "Legendary",
    description: "Dried by intense heat wave events (+84 bonus)",
    color: "#F59E0B",
  },
  {
    id: "fried",
    name: "Fried",
    bonus: 7,
    type: "temperature",
    categories: ["Food", "Cooking"],
    rarity: "Uncommon",
    description: "Fried during fried chicken events (+7 bonus)",
    color: "#D97706",
  },

  // Environmental Mutations (non-temperature environmental effects)
  {
    id: "wet",
    name: "Wet",
    bonus: 1,
    type: "environmental",
    categories: ["Water", "Weather"],
    rarity: "Common",
    description: "Affected by rain with 50% chance during rainy weather (+1 bonus)",
    color: "#3B82F6",
  },
  {
    id: "shocked",
    name: "Shocked",
    bonus: 99,
    type: "environmental",
    categories: ["Lightning", "Weather"],
    rarity: "Legendary",
    description: "Struck by lightning during thunderstorms (+99 bonus)",
    color: "#FBBF24",
  },
  {
    id: "celestial",
    name: "Celestial",
    bonus: 119,
    type: "environmental",
    categories: ["Celestial", "Stars"],
    rarity: "Legendary",
    description: "Blessed by meteor shower events (+119 bonus)",
    color: "#C7D2FE",
  },
  {
    id: "dawnbound",
    name: "Dawnbound",
    bonus: 149,
    type: "environmental",
    categories: ["Sun", "Admin"],
    rarity: "Legendary",
    description: "Admin-exclusive sun god event mutation (+149 bonus)",
    color: "#FCD34D",
  },
  {
    id: "windstruck",
    name: "Windstruck",
    bonus: 1,
    type: "environmental",
    categories: ["Weather", "Wind"],
    rarity: "Common",
    description: "Affected by strong wind weather (+1 bonus)",
    color: "#E5E7EB",
  },
  {
    id: "moonlit",
    name: "Moonlit",
    bonus: 1,
    type: "environmental",
    categories: ["Celestial", "Night"],
    rarity: "Common",
    description: "Blessed by moonlight during night events (+1 bonus)",
    color: "#C7D2FE",
  },
  {
    id: "bloodlit",
    name: "Bloodlit",
    bonus: 3,
    type: "environmental",
    categories: ["Celestial", "Blood Moon"],
    rarity: "Uncommon",
    description: "Affected by blood moon events (+3 bonus)",
    color: "#DC2626",
  },
  {
    id: "zombified",
    name: "Zombified",
    bonus: 24,
    type: "environmental",
    categories: ["Undead", "Pets"],
    rarity: "Rare",
    description: "Infected by zombie chicken pets (+24 bonus)",
    color: "#059669",
  },
  {
    id: "disco",
    name: "Disco",
    bonus: 124,
    type: "environmental",
    categories: ["Party", "Admin"],
    rarity: "Legendary",
    description: "Admin-exclusive disco event mutation (+124 bonus)",
    color: "#EC4899",
  },
  {
    id: "pollinated",
    name: "Pollinated",
    bonus: 2,
    type: "environmental",
    categories: ["Insects", "Bees"],
    rarity: "Uncommon",
    description: "Pollinated by bee swarm events or bee pets (+2 bonus)",
    color: "#FCD34D",
  },
  {
    id: "honeyed",
    name: "HoneyGlazed",
    bonus: 4,
    type: "environmental",
    categories: ["Insects", "Sweet"],
    rarity: "Uncommon",
    description: "Glazed with honey from honey sprayers and bumblebee pets (+4 bonus)",
    color: "#F59E0B",
  },
  {
    id: "voidtouched",
    name: "Voidtouched",
    bonus: 134,
    type: "environmental",
    categories: ["Void", "Admin"],
    rarity: "Legendary",
    description: "Admin-exclusive black hole event mutation (+134 bonus)",
    color: "#000000",
  },
  {
    id: "twisted",
    name: "Twisted",
    bonus: 4,
    type: "environmental",
    categories: ["Weather", "Storm"],
    rarity: "Uncommon",
    description: "Twisted by tornado events (+4 bonus)",
    color: "#6B7280",
  },
  {
    id: "plasma",
    name: "Plasma",
    bonus: 4,
    type: "environmental",
    categories: ["Energy", "Admin"],
    rarity: "Uncommon",
    description: "Admin-exclusive laser event mutation (+4 bonus)",
    color: "#8B5CF6",
  },
  {
    id: "heavenly",
    name: "Heavenly",
    bonus: 4,
    type: "environmental",
    categories: ["Divine", "Admin"],
    rarity: "Uncommon",
    description: "Admin-exclusive floating event mutation (+4 bonus)",
    color: "#FDE047",
  },
  {
    id: "choc",
    name: "Choc",
    bonus: 1,
    type: "environmental",
    categories: ["Food", "Sweet"],
    rarity: "Common",
    description: "Covered in chocolate from chocolate rain or spray (+1 bonus)",
    color: "#92400E",
  },
  {
    id: "meteoric",
    name: "Meteoric",
    bonus: 124,
    type: "environmental",
    categories: ["Space", "Admin"],
    rarity: "Legendary",
    description: "Admin-exclusive meteor event mutation (+124 bonus)",
    color: "#7C2D12",
  },
  {
    id: "alienlike",
    name: "Alienlike",
    bonus: 99,
    type: "environmental",
    categories: ["Alien", "Space"],
    rarity: "Legendary",
    description: "Transformed by alien invasion events (+99 bonus)",
    color: "#10B981",
  },
  {
    id: "galactic",
    name: "Galactic",
    bonus: 119,
    type: "environmental",
    categories: ["Space", "Cosmic"],
    rarity: "Legendary",
    description: "Enhanced by space travel events (+119 bonus)",
    color: "#1E1B4B",
  },
  {
    id: "verdant",
    name: "Verdant",
    bonus: 3,
    type: "environmental",
    categories: ["Nature", "Growth"],
    rarity: "Uncommon",
    description: "Enhanced by red parrot pets or solar flare events (+3 bonus)",
    color: "#16A34A",
  },
  {
    id: "paradisal",
    name: "Paradisal",
    bonus: 99,
    type: "environmental",
    categories: ["Paradise", "Combination"],
    rarity: "Legendary",
    description: "Perfect combination of Verdant + Sundried (+99 bonus)",
    color: "#FDE047",
  },
  {
    id: "drenched",
    name: "Drenched",
    bonus: 4,
    type: "environmental",
    categories: ["Water", "Tropical"],
    rarity: "Uncommon",
    description: "Soaked by tropical rainforest events (+4 bonus)",
    color: "#0EA5E9",
  },
  {
    id: "wiltproof",
    name: "Wiltproof",
    bonus: 3,
    type: "environmental",
    categories: ["Resilience", "Pets"],
    rarity: "Uncommon",
    description: "Protected by bird of paradise pets (+3 bonus)",
    color: "#059669",
  },
  {
    id: "aurora",
    name: "Aurora",
    bonus: 89,
    type: "environmental",
    categories: ["Celestial", "Light"],
    rarity: "Legendary",
    description: "Blessed by northern lights events (+89 bonus)",
    color: "#8B5CF6",
  },
  {
    id: "cloudtouched",
    name: "Cloudtouched",
    bonus: 4,
    type: "environmental",
    categories: ["Sky", "Spray"],
    rarity: "Uncommon",
    description: "Touched by clouds from cloud spray (+4 bonus)",
    color: "#E0E7FF",
  },
  {
    id: "sandy",
    name: "Sandy",
    bonus: 2,
    type: "environmental",
    categories: ["Weather", "Desert"],
    rarity: "Uncommon",
    description: "Affected by sandstorm events (+2 bonus)",
    color: "#F59E0B",
  },
  {
    id: "clay",
    name: "Clay",
    bonus: 2,
    type: "environmental",
    categories: ["Soil", "Earth"],
    rarity: "Uncommon",
    description: "Wet crops that dry on sandy soil (+2 bonus)",
    color: "#A16207",
  },
  {
    id: "ceramic",
    name: "Ceramic",
    bonus: 49,
    type: "environmental",
    categories: ["Crafted", "Combination"],
    rarity: "Rare",
    description: "Sundried crops on clay soil (+49 bonus)",
    color: "#F97316",
  },
  {
    id: "amber",
    name: "Amber",
    bonus: 9,
    type: "environmental",
    categories: ["Preservation", "Ancient"],
    rarity: "Uncommon",
    description: "Preserved in amber spray or by terror bird pets (+9 bonus)",
    color: "#F59E0B",
  },
  {
    id: "old-amber",
    name: "OldAmber",
    bonus: 19,
    type: "environmental",
    categories: ["Ancient", "Time"],
    rarity: "Rare",
    description: "Amber preserved for 24 hours (+19 bonus)",
    color: "#D97706",
  },
  {
    id: "ancient-amber",
    name: "AncientAmber",
    bonus: 49,
    type: "environmental",
    categories: ["Ancient", "Ultimate"],
    rarity: "Rare",
    description: "Old Amber preserved even further (+49 bonus)",
    color: "#92400E",
  },
  {
    id: "tempestuous",
    name: "Tempestuous",
    bonus: 11,
    type: "environmental",
    categories: ["Storm", "Combination"],
    rarity: "Uncommon",
    description: "Combination of Windstruck + Twisted + Sandy (+11 bonus)",
    color: "#374151",
  },
  {
    id: "friendbound",
    name: "Friendbound",
    bonus: 69,
    type: "environmental",
    categories: ["Social", "Friendship"],
    rarity: "Rare",
    description: "Enhanced by friendship jar continuous benefits (+69 bonus)",
    color: "#F472B6",
  },
  {
    id: "infected",
    name: "Infected",
    bonus: 74,
    type: "environmental",
    categories: ["Undead", "Events"],
    rarity: "Rare",
    description: "Infected during zombie invasion events (+74 bonus)",
    color: "#16A34A",
  },
  {
    id: "tranquil",
    name: "Tranquil",
    bonus: 19,
    type: "environmental",
    categories: ["Peace", "Zen"],
    rarity: "Rare",
    description: "Blessed by zen aura events or special pets (+19 bonus)",
    color: "#10B981",
  },
  {
    id: "chakra",
    name: "Chakra",
    bonus: 4,
    type: "environmental",
    categories: ["Spiritual", "Pets"],
    rarity: "Uncommon",
    description: "Enhanced by fox spirit pet abilities (+4 bonus)",
    color: "#A855F7",
  },
]

export const cropCategories = Array.from(new Set(crops.flatMap((crop) => crop.categories)))
export const mutationCategories = Array.from(new Set(mutations.flatMap((mutation) => mutation.categories)))

export const rarityColors = {
  Common: "text-gray-600 bg-gray-100",
  Uncommon: "text-green-600 bg-green-100",
  Rare: "text-blue-600 bg-blue-100",
  Legendary: "text-purple-600 bg-purple-100",
  Mythical: "text-pink-600 bg-pink-100",
  Divine: "text-yellow-600 bg-yellow-100",
  Prismatic: "text-indigo-600 bg-indigo-100",
  Transcendent: "text-red-600 bg-red-100",
}

export const rarityBorders = {
  Common: "border-gray-300",
  Uncommon: "border-green-300",
  Rare: "border-blue-300",
  Legendary: "border-purple-300",
  Mythical: "border-pink-300",
  Divine: "border-yellow-300",
  Prismatic: "border-indigo-300",
  Transcendent: "border-red-300",
}
